[WIP] SILGen differentiability witneses from `@derivative` attribute.
Do not generate implicit `@differentiable` attributes during `@derivative`
attribute type-checking. Instead, directly SILGen differentiability witnesses
from `@derivative` attribute.

Update TBDGen to support `@derivative` attributes.
Revert ASTScope hacks for implicit `@differentiable` attributes: TF-815.

Blocked by handling of external original functions with no `@differentiable`
attribute but a registered `@derivative` function.

Example: `Float.+` has a `@derivative` function but no `@differentiable`
attribute:

```
@differentiable
func foo(_ x: Float, _ y: Float) -> Float {
  x + y
}
```

Currently, this fails with:
```
foo.swift:3:5: error: expression is not differentiable
  x + y
    ^
foo.swift:3:5: note: cannot differentiate functions that have not been marked '@differentiable' and that are defined in other files
  x + y
    ^
```

`Float.+` is SILGen'd as an external function declaration with no
differentiability witnesses:
```
// static Float.+ infix(_:_:)
sil [transparent] [serialized] @$sSf1poiyS2f_SftFZ : $@convention(method) (Float, Float, @thin Float.Type) -> Float
```

It's not clear how to support this. The `@derivative` function of `Float.+` of
the standard library is never referenced, so no differentiability witness for
`Float.+` is ever SILGen'd.

Ideas considered:
- TF-988: Create differentiability witness declarations in
  `SILFunctionBuilder::addFunctionAttributes` instead of
  `SILGenModule::postEmitFunction`.
  - Counterpoint: doing this doesn't solve the problem, because `@derivative`
    functions for external functions aren't actually SILGen'd.
- Keep the current design: generate implicit `@differentiable` attributes on
  the original function from `@derivative` attributes.
  - This is not ideal because implicit `@differentiable` attributes trigger
    all kinds of code paths. The current behavior may not be intended in all
    circumstances, e.g. it's probably not intended to generate implicit
    `@differentiable` attribute on protocol requirement definitions when
    registering a default derivative implementation (TF-982).
- Generate some new implicit attribute like `@differentiable`.
  - This has the advantange of not triggering `@differentiable` attribute code
    paths, like type-checking and ASTScope stuff.

Todos:
- Implement `@derivative` attribute serialization, which is unblocked by this
  patch. Currently, serialization encounters and infinite loop between
  serializing the implicit `@differentiable` attribute and the `@derivative`
  attribute.